name: Build Gradle project

on:
  pull_request:
    branches:
      - kh-test
  push:
    branches:
      - kh-test


permissions:
  contents: write

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - run: touch ./src/main/resources/application.properties
      - run: echo "${{ secrets.ACTIONS_BUILD_SECRETS }}" > ./src/main/resources/application.properties

      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run build with Gradle Wrapper
        run: ./gradlew build

      - name: Start App
        run: |
          nohup ./gradlew bootRun &
          sleep 60  # give some time for the app to start

      - name: Fetch Swagger Documentation (OAS 3)
        run: curl http://localhost:8080/v3/api-docs.yaml > api-docs.yaml

      - name: Commit OpenAPI YAML to Repo
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/innovationCamp/messenger-service.git
          git add api-docs.yaml
          git commit -m "Updated api-docs.yaml" || echo "No changes to commit"
          git push origin HEAD:documentation --force

          
